dist: trusty
language: rust
services: docker
sudo: required

matrix:
  include:
    - env: TARGET=x86_64-unknown-linux-gnu
    - env: TARGET=x86_64-pc-windows-gnu

before_install:
  - set -e 
  - rustup self update

install: 
  - sh ci/install.sh
  - source ~/.cargo/env || true

script: 
  - sh ci/lint-check.sh
  - sh ci/build.sh

before_deploy:
  - sh ci/release.sh

deploy:
  provider: releases
  skip_cleanup: true
  api_key: ${GITHUB_API_TOKEN}
  file_glob: true
  file: build/*
  on: 
    tags: true