on: [push]

name: Premerge checks

jobs:

  build:
    name: Build
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout source
        uses: actions/checkout@master
      
      - name: Install Rust
        if: matrix.os == 'macOS-latest'
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      
      - name: Build binaries
        uses: actions-rs/cargo@v1
        with:
          command: build
    
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@master

      - name: Install Rust components
        run: rustup component add rustfmt clippy

      - name: Rust fmt 
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      
      - name: Clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-targets --all-features -- -D warnings